### ISSUE TITLE
Rec Sensor show bad "data" value

### ISSUE THREAD

**Issue by sagitt** [kodi1/tvh_rec#6]
As you can see in the image, the rec sensow show in data the below value.
Is this correct?

i'm using last hass version (0.116.2) and this tvh: HTS Tvheadend 4.2.9~pre+201911151752-0~built202006011817~git5bdcfd8~ubuntu20.04.1

if this is an error, you can fix this?

![Schermata 2020-10-14 alle 16 09 17](https://user-images.githubusercontent.com/169086/96001104-f61cba00-0e37-11eb-8a89-1ce73d3cac84.png)

> [{"title_default": "$title", "line1_default": "$episode", "line2_default": "$studio $release", "line3_default": "$runtime $date $time", "line4_default": "$number", "icon": "mdi:arrow-down-bold"}]

**Comment by iHaveAstream** [comment]
Almost same issue here with Hass 116.4 and TVH 4.3~9ed76c0:
![tvh_rec](https://user-images.githubusercontent.com/62019393/96834353-28cf3f80-1442-11eb-8274-1e6549a78cd7.png)

It would be nice if that could be fixed so that the details popup shows well-formatted information.
Also it would be cool if this addon could show at a glance in a card which are the next recordings incl. their respective titles, channels. Currently the only card layout I can get is like:
![card_tvh_rec](https://user-images.githubusercontent.com/62019393/96834649-a430f100-1442-11eb-818e-b06acbbfc581.png)

Thanks!

**Comment by kodi1** [comment]
That data is needed by [Upcoming Media Card](https://github.com/custom-cards/upcoming-media-card)

**Comment by sagitt** [comment]
> That data is needed by [Upcoming Media Card](https://github.com/custom-cards/upcoming-media-card)

thanks work.
maybe a note for it.
